### ISSUE TITLE
Request data hash always returns empty byte array

### ISSUE THREAD

**Issue by vaspopinex** [ikyriak/IdempotentAPI#58]
The following code in the GetRequestsDataHash method doesnt seem to work as expected. In our scenarios we keep getting the result always being a byte[0]. Which thus results in the unwanted behaviour of requests with different payloads and same idempotency key are treated as the same.

``` csharp
httpRequest.EnableBuffering();

if (httpRequest.Body.CanRead
    && httpRequest.Body.CanSeek)
{
    using MemoryStream memoryStream = new();
    httpRequest.Body.Position = 0;

    await httpRequest.Body.CopyToAsync(memoryStream).ConfigureAwait(false);
    requestsData.Add(memoryStream.ToArray());

```

**Comment by ikyriak** [comment]
Hello @vaspopinex 

Thank you for reporting this issue 🙏
I will fix it as soon as possible.

**Comment by ikyriak** [comment]
Hello @vaspopinex 

I have prepared the following pre-release packages to fix this issue.
When you have time, could you please check that it is fixed in your use-case?

- https://www.nuget.org/packages/IdempotentAPI/2.1.1-prerelease-01
- https://www.nuget.org/packages/IdempotentAPI.MinimalAPI/2.1.1-prerelease-01
