### ISSUE TITLE
FastEndpoints support?

### ISSUE THREAD

**Issue by CaptainPowerTurtle** [ikyriak/IdempotentAPI#72]
Have anyone tried to use this with FastEndpoints?: https://fast-endpoints.com/

I followed the setup/examples for the minimal api, and it is almost working. It is caching the response, but when i call the endpoint again, using the same key, i get no data back.

I tested it with the MinimalApi endpoints, and it works as it should.

**Comment by ikyriak** [comment]
Hello @CaptainPowerTurtle,

Thank you for opening this issue.
I have not tried using it with FastEndpoints, but I will try to when I have some free time.

**Comment by dj-nitehawk** [comment]
@ikyriak i'm the lead maintainer of fastendpoints and thought you might find the following info interesting:

![screen-record-1716003403](https://github.com/ikyriak/IdempotentAPI/assets/7043768/a490eac5-171c-4bdf-885f-49a74559b95e)

so if there's any interest in adding FE support, you'd have to grab the response DTO instance from the `HttpContext.Items` dictionary for storing in the cache, since the FE minimal api delegate doesn't return anything itself.

let me know if there's anything we can do from our end to facilitate compatibility.

thanks!

**Comment by ikyriak** [comment]
Hello @dj-nitehawk,

Thank you for providing me with this helpful information 🙏

**Comment by ikyriak** [comment]
Hello @dj-nitehawk,

When using Minimal APIs, in the `InvokeAsync(EndpointFilterInvocationContext context, EndpointFilterDelegate next)` method on an `IEndpointFilter`, I have access to the actual request class (e.g., the DTO in a POST request).

However, this is not available when using `FastEndpoints`. Is there a way to get the request body?
![image](https://github.com/ikyriak/IdempotentAPI/assets/44930763/b139e2b5-594b-48d2-9e89-7e90b7c9d026)

This is needed not to accept the same idempotency key for different request payloads.
![image](https://github.com/ikyriak/IdempotentAPI/assets/44930763/cef08902-5fd2-41c9-a6b3-4cb97ac008c0)

**Comment by dj-nitehawk** [comment]
i see... the trouble is, the following is how fastendpoints registers the minimal api delegates for endpoints:

https://github.com/FastEndpoints/FastEndpoints/blob/3422ada67cfd628527acb21034dae4f6a513607c/Src/Library/Main/MainExtensions.cs#L117-L120

so, you won't have access to a typed request dto at the outer level of `IEndpointFilter`s. the request dto is created inside FE's endpoint handler. 

you could maybe read the request stream via `HttpContext.Request.Body` for the purpose of building the cache-key. that is what we're doing in our [idempotency implementation](https://github.com/FastEndpoints/FastEndpoints/blob/3422ada67cfd628527acb21034dae4f6a513607c/Src/Library/Endpoint/Idempotency/IdempotencyPolicy.cs#L56-L93). which, may not work for you since our implementation is [based on the OutputCaching middleware](https://fast-endpoints.com/docs/idempotency).

i'm assuming you need access to the request dto for building the cache-key by iterating the properties of the dto via reflection yes? in which case, i'm out of ideas 🤔

**Comment by ikyriak** [comment]
Thank you for your response, @dj-nitehawk. When FastEndpoints are used, I will read the request stream via `HttpContext.Request.Body`. 🙏

**Comment by ikyriak** [comment]
Hello @CaptainPowerTurtle,

I have pushed the following prerelease versions that support FastEndpoints:
- [IdempotentAPI v2.5.0-issue-72-01](https://www.nuget.org/packages/IdempotentAPI/2.5.0-issue-72-01)
- [IdempotentAPI.MinimalAPI v3.1.0-issue-72-01](https://www.nuget.org/packages/IdempotentAPI.MinimalAPI/3.1.0-issue-72-01)

**Comment by ikyriak** [comment]
This issue is resolved in the following stable version:
- [IdempotentAPI v2.5.0](https://www.nuget.org/packages/IdempotentAPI/2.5.0)
- [IdempotentAPI.MinimalAPI v3.1.0](https://www.nuget.org/packages/IdempotentAPI.MinimalAPI/3.1.0)
